#
#  _____ _       _____ _  __
# |_   _| |     |_   _| |/ /
#   | | | |_ ____ | | | ' / ___ _ __
#   | | | __|_  / | | |  < / _ \ '_ \
#  _| |_| |_ / / _| |_| . \  __/ | | |
# |_____|\__/___|_____|_|\_\___|_| |_|
#

JoinMessage: "§a+§7{player}"
QuitMessage: "§c-§7{player}"
